[starxONEDRIVE]
type = drive
scope = drive
token = {"access_token":"ya29.a0AT3oNZ9RiOHxspYgSCtV9-87JBBVHJ32L1ihYZLfEeTr8_hHMAeKTYX4wuZJG786mF-MrslRQ5QeWfDZIRKdWQ3cAVYJt82rn3Gz1-1j2IXxzSKlsDw8PDxFBcY0mqxo683hWZ0bCpP86d6kLlzPq8r9KaUVGMq-RoTaB4QpVLRIXFMSogoHcvHxQ-HKP-fvykGJbCUaCgYKAUYSARISFQHGX2MiHXZYJOCCUtLv8uR0n81pWQ0206","token_type":"Bearer","refresh_token":"1//0hIoA6xzlFbprCgYIARAAGBESNwF-L9Irtz-ryC-nR90hMj-EzmU4yucTmwhjHXBOQ3bd2TkQ9YgA8tGFe-pGhsvJf1msJn3HoWM","expiry":"2026-07-01T20:20:26.285242302-04:00","expires_in":3599}
team_drive =
