[starxONEDRIVE]
type = drive
scope = drive
token = {"access_token":"ya29.a0AT3oNZ-79ZOd0W-BTVR2M2Jy21XxChpUmKRxBbMiOoIMBdvGK2bhQXEtVPbKyy0a0NngKNBrrG6Bh5NOYsQ-GH_ro1SB9WaJ4YqVr-tLF7SMJSKOQcwVAm0vILb5jacvqrdsc63OUIg1QG-dt8KLP57IyoZ_6hpYpuOl1kbJ6mRoFXT7PxXBs7ssLj5N7NuCvRbUm48aCgYKAWYSARISFQHGX2Mitu1QQhWzUzI5yu6JryKrjw0206","token_type":"Bearer","refresh_token":"1//0h4vt3U2diRpvCgYIARAAGBESNwF-L9IrxY97cn7f1Mg943guW-80OaXo1J_vcsAng_mn417qoqi7MdiIlMcuXu8V17exm5oxD4M","expiry":"2026-07-02T00:43:33.762364228-04:00","expires_in":3599}
team_drive =
