[starxONEDRIVE]
type = drive
scope = drive
token = {"access_token":"ya29.a0ARGnu0ZTQILLrJ1Y4FxjXCFwOtaZcCEXerM-WgzYYgcWnGuEX28ESuz6iy1W3lMX1VsRDPDxqi3iQmT2jjUhKnDfWUBS9hf4VazM84abpmcoEoVBFgI0a6z1x427PLrerAg2KpdUnNg1JI2jOkQ4xGPLqpFIw0gHvx1peAMXwYzTm-IAYaWoajMVHO6GTmf3rqxMakQaCgYKAf8SARISFQHGX2MiJ1KKWesi05WB2YD_6FddeA0206","token_type":"Bearer","refresh_token":"1//0h7xc3XfemghICgYIARAAGBESNwF-L9IrwBk6xvGBbu1iNj9kDofpgaisz2_AzvSoq5eG515TyU5J1hLzOPbqwtNsBMN5wKBPnRU","expiry":"2026-07-09T18:40:45.881294688-04:00","expires_in":3599}
team_drive =
